/*
* Each new term in the Fibonacci sequence is generated by 
* adding the previous two terms.By starting with 1 and 2, 
* the first 10 terms will be:
* 
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* 
* Write a function that, given N, finds the sum of all the 
* even numbers within the first N terms of the Fibonacci 
* sequence.
*
* For instance
*
* evenFib(10) = 44 // (2 + 8 + 34)
* evenFib(5) = 10 // (2 + 8 = 10)
* evenFib(2) = 2
* evenFib(1) = 0
*/

var evenFib = function(n) {

};